source 'https://rubygems.org/'
ruby '2.1.6'
gem 'nokogiri', '~> 1.6.0'

gem 'rails', '~> 3.2.20'
gem 'sqlite3', :platform => :ruby
gem 'activerecord-jdbcsqlite3-adapter', :platforms => :jruby

gem 'pry', group: :development
gem 'consistent-hashing'
gem 'request_store'
gem 'recommendable', path: '/Users/carpedm20/git/recommendable', branch: 'evaluation'
#gem 'recommendable', path: '/root/git/recommendable', branch: 'evaluation'

gem 'pg'
gem 'test-unit', '~> 3.0'
gem "redis"
gem "hiredis"
